### Problem 1
Construct the following arrays without listing all the elements. For example, you should use **np.ones(3)** to generate a array *array([1, 1, 1])* instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [1]:
import numpy as np

#### Your code here

arr = np.arange(11.0)
print arr

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [16]:
#### Your code here

arr = np.linspace(0,23,7)
print arr


[  0.           3.83333333   7.66666667  11.5         15.33333333
  19.16666667  23.        ]


(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [2]:
#### Your code here

arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.matrix(arr1)
print arr2

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(4) Create a 5x5 matrix with row values ranging from 0 to 4.

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [20]:
#### Your code here

arr1 = range(0,5)*5
arr2= np.matrix(arr1).reshape(5,5)
print arr2


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


(5) A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)


In [105]:
#### Your code here  


def isMagic(arr):
    
    # assumption: arr is a 2-dimentional NumPy array 
    
    is_magic_flag = True
    
    # check for square property
    if arr.shape[0] != arr.shape[1]:
        is_magic_flag = False
    
    # check for items being in (1,2,3,...,n^2)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr[i,j] not in set(range(1,arr.shape[0]**2+1)):
                is_magic_flag = False
    
    # check that each item only appears once
    lis = []
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            lis.append(arr[i,j])
    if len(lis) != len(set(lis)):
        is_magic_flag = False
        
    # check for sum of rows, columns and diags
    s = set()
    s.add(np.diag(arr).sum())    # main diagonal sum
    s.add(np.diag(arr.T).sum())  # second diagonal sum
    for i in range(arr.shape[0]):
        s.add(arr.sum(axis=0)[i])  # column sums
        s.add(arr.sum(axis=1)[i])  # row sums
    if len(s) != 1:
        is_magic_flag = False 

    return is_magic_flag
        
        
    

Here are some tests:

In [106]:
test1 = np.array([[0, 1], 
                  [1, 0]])
isMagic(test1) # False


False

In [107]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True    

True

In [108]:
test3 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test3) # True

True

In [109]:
test4 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test4) # True

True

In [110]:
test5 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
isMagic(test5) # True

True

### Problem 2

According to this picture, does the "Petal Length" of different species has significant difference? Using the **Analysis of Variance** varify your answer.

![iris](http://slides.nycdatascience.com/BOOTCAMP3/content/week6/pic/scatter.png)

In [6]:
import pandas as pd
from scipy import stats
from sklearn import datasets
raw_data = datasets.load_iris()

Species = raw_data['target_names'][raw_data['target']]
PetalLength = raw_data.data[:,2]
PetalWidth = raw_data.data[:,3]

PetalLength
Species

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [8]:
#### Your code here

#petal_len_setosa = PetalLength[0:50]
#petal_len_versicilor = PetalLength[50:100]
#petal_len_virginica = PetalLength[100:150]

petal_len_setosa = PetalLength[Species == 'setosa']
petal_len_versicolor = PetalLength[Species == 'versicilor']
petal_len_virginica = PetalLength[Species == 'virginica']


stats.f_oneway(petal_len_setosa, petal_len_versicilor, petal_len_virginica)

F_onewayResult(statistic=1179.0343277002194, pvalue=3.0519758018278374e-91)

### Problem 3


We discuss random sampling in the class, which helps when exact solution is hard to obtain. For example, we know that the area of a circle is $\pi \times r^2 \text{, where } r \text{ is the radius of the circle. }$ But we don't know how to approximate the number $\pi$.

Monte Carlo simulation can help.

<img src=monte_carlo.png width=330/>

- Use `np.random.uniform` function to generate 2000 two dimensional samples. `uniform` indicates that the likelihood for any number from **-1 to 1** occurs is uniform. The shape of your sample should look like below (of course the actual numbers can be different)
```
array([[-0.53277773, -0.93122476],
        [ 0.16017788, -0.74177143],
        [ 0.37248292,  0.36734988],
        ..., 
        [ 0.5314644 , -0.50411338],
        [ 0.12208452,  0.6242463 ],
        [ 0.74767075, -0.56486567]])
```
Therefore all the samples fall in the $[-1, 1] \times [-1, 1] \text{ box.}$

In [11]:
import numpy as np
#### Your code here
trials = 20000
lis=[]
for i in range(trials):
    lis.append([np.random.uniform(-1,1), np.random.uniform(-1,1)])
    

- The probability of points being in the circle is the ratio between the area of the circle and the area of the $[-1, 1] \times [-1, 1] \text{ box.}$ More precisely,

$$\text{Probability} \big( \text{points falling in the circle} \big) = \frac{\text{area of the circle}}{\text{area of the rectangle}} = \frac{\pi}{4},$$

From the sample you generate in the last problem, estimate the probability of falling in the circle, then approximate $\pi$.

In [12]:
#### Your code here

sum_circle=0
for i in range(trials):
    x = lis[i][0]
    y = lis[i][1]
    if (x**2 + y**2) <= 1:
        sum_circle = sum_circle + 1
        

print 'Pi is approximately equal to: %f' %(4.0*sum_circle/trials)

Pi is approximately equal to: 3.149200
